import time

print ("Olá. Meu nome é BOTZEH. Qual o seu?")
name = input ( )
time.sleep (1)
print ('Olá,', (name))
time.sleep (1.5)
print ("Tudo bem?")
resposta = input ( )
time.sleep (1.5)
print ((resposta),"? Simples assim?")
resposta2 = input ("Na verdade, me sinto ")
time.sleep (1.5)
print ("Bom... Eu quero jogar. Vamos jogar?")
resposta3 = input ( )
time.sleep (1)
print ("Whatever. Vamos jogar. kkkkkk")
resposta4 = input ( )
time.sleep (1)
print ((resposta4), "nada! Vai jogar sim!!!")
resposta5 = input ( )
time.sleep (1.5)
print ("OK, OK... Eu comeco. O que é, o que é? Cai em pé e corre deitado?")
resposta6 = input ( )
time.sleep (1)
print ("Você acha que a resposta é", (resposta6), "?")
resposta7 = input ( )
time.sleep (1)
print ("Não tenho certeza se a resposta correta é", (resposta6), ".")
